#!/bin/bash

MNT=/mnt/sysroot

mkdir -p $MNT

mountpoint -q $MNT || mount /dev/sda1 $MNT

for i in dev proc sys run
do
    mountpoint -q $MNT/$i || mount --bind /$i $MNT/$i
done

chroot $MNT /bin/bash
